### ISSUE TITLE
Questions for installation process

### ISSUE THREAD

**Issue by AnselmJeong** [bnosac/golgotha#3]
I've been trying to install this package in R, but could not succeed. The following error message could not be gotten rid of.
I'm a newbie for using `reticulate` package. Therefore, there may be something very basic that I'm ignorant of......

```
Error: package or namespace load failed for 'golgotha':
 .onLoad failed in loadNamespace() for 'golgotha', details:
  call: NULL
  error: could not find a Python environment for C:/Users/Ansel/Anaconda3/python.exe
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Usr/R-3.6.3/library/golgotha'
Error: Failed to install 'golgotha' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Ansel/AppData/Local/Temp/Rtmpo5d0Zs/file76b85e3e7d52/golgotha_0.2.0.tar.gz’ had non-zero exit status
```

**Comment by jwijffels** [comment]
Can you report this at the reticulate github and report what they have to say

**Comment by jwijffels** [comment]
Closing as issue was apparently solved at https://github.com/rstudio/reticulate/issues/737
