### ISSUE TITLE
Error in building wheels for collected packages: torch

### ISSUE THREAD

**Issue by rdatasculptor** [bnosac/golgotha#5]
first all thank you for this exciting new package! I can't wait to try out models like BERT in R.

When I run this code:

```
devtools::install_github("bnosac/golgotha", INSTALL_opts = "--no-multiarch")
library(golgotha)
transformer_download_model("bert-base-multilingual-uncased")
```

I run into some errors.
After calling `transformer_download_model("bert-base-multilingual-uncased")` it is asked to install r miniconda. The first error in the installation precess that appears is this one:

 ```
Building wheel for torch (setup.py): started
  Building wheel for torch (setup.py): finished with status 'error'
```

Since I am rather new in Python I am not completely sure if this is the right place to put this issue. Maybe I need to go to the reticulate github?

**Comment by jwijffels** [comment]
Hi @rdatasculptor 
I think you should ask this at the reticulate package while copying the full error message alongside the golgotha DESCRIPTION file which shows that the package needs torch. I have no idea on the reason of the error.

**Comment by rdatasculptor** [comment]
Okay thank you for your response. I filed an issue here: https://github.com/rstudio/reticulate/issues/740

**Comment by rdatasculptor** [comment]
there seemed to be a conflict between different Python enverionments. Now it works!

**Comment by jwijffels** [comment]
I looked to the thread at the reticulate package. 
That looked like a typical python package environment problem. Anaconda, miniconda, conda, pip, easy_install, python 2, python 3, package versions, virtual environments, conda activate, venv, torch which only works on 64bit, ... lovely...

**Comment by rdatasculptor** [comment]
It's a drag indeed... 😊, the installation processes of python is quite confusing for me currently. At least it makes me aware of the straightforward R architecture.

**Comment by jwijffels** [comment]
Yes. The R community is spoiled with CRAN.
