### ISSUE TITLE
Functions for similarity and classification 

### ISSUE THREAD

**Issue by rdatasculptor** [bnosac/golgotha#7]
Good morning Jan,

Just curious, do you have plans to add functions to the package that make it easier to do things like finding similar words (or sentences), text classification (a bit like you did in ruimtehol) and prediction of next word in a sentence?

Thanks for making BERT available in R!

**Comment by jwijffels** [comment]
Haven't got many plans currently on this.
- About similar sentences
I think you could use the text similarity functions from ruimtehol (embedding_similarity) which does cosine / dot product similarity but other similarities are easily available in other packages. 
The idea of the package is just to have the embeddings, nothing more currently. 
- About similar words
These are basically subwords, don't know if that is really usefull still
- About text classification
I think you easily plug in the embeddings in classification models like SVM / glmnet / boosting / randomforests / other more traditional stat models, maybe not in sequence models like crfsuite currently for this I might work on brown clustering a bit. In the core the result is just a matrix of numbers.
- About next word in a sequence. I've put an example in the vignette. But haven't worked on a business case where this seemed important - that was more toying around.
- About data augmentation (replacing words with other words for having more training data), I might look into that but it's not top priority for me now

**Comment by rdatasculptor** [comment]
Thank you for your answer! And thanks for pointing me into the direction of other classification algorithms. I will toy around. Thanks again for this package!

**Comment by jwijffels** [comment]
FYI. You can easily use quanteda.textmodels package from @kbenoit 
Like this.

```
library(quanteda)
library(quanteda.textmodels)
library(golgotha)
x <- data.frame(doc_id = c("doc_1", "doc_2"),
                text = c("give me back my money or i'll call the police.",
                         "talk to the hand because the face don't want to hear it any more."),
                y = c("yes", "no"),
                stringsAsFactors = FALSE)
model <- transformer("bert-base-multilingual-uncased")

embedding <- predict(model, x, type = "embed-sentence")
dtm <- as.dfm(embedding)
textmodel_svm(x = dtm, y = ...)
```

With glmnet that means you already have the X part of the model.
```
library(glmnet)
cv.glmnet(x = embedding, ...)
```

good luck

**Comment by rdatasculptor** [comment]
That's brilliant! Thank you. I will start here.

**Comment by rdatasculptor** [comment]
Maybe you think this `FARM` algorithm interesting as well: https://towardsdatascience.com/fine-tuning-bert-for-text-classification-with-farm-2880665065e2

**Comment by jwijffels** [comment]
@rdatasculptor thanks for the links
I haven't looked to this in detail but I have the impression that all this finetuning just finds a linear or non-linear combination of the embeddings to predict something and it is not fintuning the existing embeddings any more. Is that the case.
FYI. Last week I created a wrapper around https://github.com/bnosac/word2vec, working on all platforms as existing word2vec implementations in R only worked on Linux. I'm pushing it to cran soon. So now if you are interested in vector representations of words, you can use https://github.com/bnosac/word2vec, https://github.com/bnosac/ruimtehol, https://github.com/bnosac/golgotha or Glove https://cran.r-project.org/web/packages/text2vec/vignettes/glove.html or just singular value decomposition of matrices using https://cran.r-project.org/web/packages/irlba/index.html

**Comment by rdatasculptor** [comment]
very nice!
