### ISSUE TITLE
how to use gpu / multicore?

### ISSUE THREAD

**Issue by KnutJaegersberg** [bnosac/golgotha#8]
Hi, is it possible to use golgotha on gpu for faster embedding assignment?
tried to set settings for gpu with the torch library, but it did not work. 
played around for parallelization in rr, but did not find an efficient flow for multicore usage. 
looked like i had to reload the bert model for all r process forks. thats slow. 
is multicore usage or gpu usage possible with golgotha?

**Comment by jwijffels** [comment]
This is why the package is called golgotha. 

If you want it to work on GPU, you can change the code here https://github.com/bnosac/golgotha/blob/master/inst/python/BERT.py#L36, make a pull request. Please also add some unit test to the package so that I know changes are done correctly.

**Comment by KnutJaegersberg** [comment]
jap, got that. 

handy to speed things up though, thanks for the clue!
